<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit27067fc0f851f6674ec52b687e30612c
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Src\\' => 4,
        ),
        'D' => 
        array (
            'Devbr\\' => 6,
        ),
        'C' => 
        array (
            'Config\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Src\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
        'Devbr\\' => 
        array (
            0 => __DIR__ . '/..' . '/devbr/router',
        ),
        'Config\\' => 
        array (
            0 => __DIR__ . '/..' . '/devbr/router/Config',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit27067fc0f851f6674ec52b687e30612c::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit27067fc0f851f6674ec52b687e30612c::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
