<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Src\\' => array($baseDir . '/src'),
    'Devbr\\' => array($vendorDir . '/devbr/router'),
    'Config\\' => array($vendorDir . '/devbr/router/Config'),
);
